import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import '../../features/events/domain/tickr_event.dart';

// This is the Riverpod provider that will hold our open database.
// Other parts of the app will read this to save or fetch events.
final isarProvider = Provider<Isar>((ref) {
  throw UnimplementedError('Isar database has not been initialized yet');
});

// We will call this function right before runApp()
Future<Isar> initIsarDatabase() async {
  // 1. Find the safe directory on the Android device
  final dir = await getApplicationDocumentsDirectory();

  // 2. Open the database and tell it about our TickrEvent schema
  final isar = await Isar.open(
    [TickrEventSchema], // The schema generated by build_runner
    directory: dir.path,
  );

  return isar;
}