import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import '../../features/events/domain/tickr_event.dart';
import '../../features/tasks/domain/tickr_task.dart';

// This is the Riverpod provider that will hold our open database.
// Other parts of the app will read this to save or fetch events.
final isarProvider = Provider<Isar>((ref) {
  throw UnimplementedError('Isar database has not been initialized yet');
});

// We will call this function right before runApp()
Future<Isar> initIsarDatabase() async {
  // 1. Find the safe directory on the Android device
  final dir = await getApplicationDocumentsDirectory();

  // 2. Open the database and tell it about our schemas
  final isar = await Isar.open(
    [TickrEventSchema, TickrTaskSchema], // The schemas generated by build_runner
    directory: dir.path,
  );

  return isar;
}

/// Removes all events and tasks from local storage (e.g. when switching accounts).
Future<void> wipeAllLocalTickrData(Isar isar) async {
  await isar.writeTxn(() async {
    await isar.tickrEvents.clear();
    await isar.tickrTasks.clear();
  });
}